apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: order-service

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: product-service
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9010
  selector:
    app: product-service

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: report-service
  labels:
    app: report-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9020
  selector:
    app: report-service