name: DevHour pipeline

on: [push]

jobs:
  build:
    env:
      SHA8: ${GITHUB_SHA::8}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-Configure-ci-cd-pipelines
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn clean install
      - uses: actions/upload-artifact@v3
        with:
          name: DevHour-build
          path: |
            3-Configure-ci-cd-pipelines/
  package:
    needs: build
    runs-on : ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        id: build
        with:
          name: DevHour-build
      - run: |
          docker build -t order-service:${GITHUB_SHA::8}./order-service
          docker build -t product-service:${GITHUB_SHA::8} ./product-service
          docker build -t report-service:${GITHUB_SHA::8} ./report-service
        shell: bash


#  test:
#    needs: package
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: 3-Configure-ci-cd-pipelines
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: DevHour-jars
#          path: 3-Configure-ci-cd-pipelines/staging/*.jar