name: DevHour pipeline

on: [push]

jobs:
  build:
    env:
      SHA8: ${GITHUB_SHA::8}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-Configure-ci-cd-pipelines
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn clean install
      - uses: actions/upload-artifact@v3
        with:
          name: DevHour-build
          path: |
            3-Configure-ci-cd-pipelines/
  package-and-push:
    needs: build
    runs-on : ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        id: build
        with:
          name: DevHour-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: |
          docker build -t 295899794390.dkr.ecr.eu-north-1.amazonaws.com/order-service:${GITHUB_SHA::8} ./order-service
          docker build -t 295899794390.dkr.ecr.eu-north-1.amazonaws.com/product-service:${GITHUB_SHA::8} ./product-service
          docker build -t ${{ ECR_REGISTRY }}/report-service:${GITHUB_SHA::8} ./report-service
        shell: bash


#  test:
#    needs: package
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: 3-Configure-ci-cd-pipelines
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: DevHour-jars
#          path: 3-Configure-ci-cd-pipelines/staging/*.jar