name: DevHour pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-Configure-ci-cd-pipelines
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn -Drevision=${GITHUB_SHA::7} clean install
      - uses: actions/upload-artifact@v3
        with:
          name: DevHour-build
          path: |
            3-Configure-ci-cd-pipelines/