name: DevHour pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-Configure-ci-cd-pipelines
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn clean install
      - run: cp */target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: DevHour-jars
          path: |
            3-Configure-ci-cd-pipelines/staging/*.jar
  package:
    needs: build
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        id: jars
        with:
          name: DevHour-jars
          path: 3-Configure-ci-cd-pipelines/staging
      - run: cd ${{steps.jars.outputs.download-path}} && ls -la
        shell: bash
      - run: |
          docker build -t order-service ./3-Configure-ci-cd-pipelines/order-service --build-arg targetFolder=${{steps.jars.outputs.download-path}}
          docker build -t product-service ./3-Configure-ci-cd-pipelines/product-service --build-arg targetFolder=${{steps.jars.outputs.download-path}}
          docker build -t report-service ./3-Configure-ci-cd-pipelines/report-service --build-arg targetFolder=${{steps.jars.outputs.download-path}}
        shell: bash


#  test:
#    needs: package
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: 3-Configure-ci-cd-pipelines
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: DevHour-jars
#          path: 3-Configure-ci-cd-pipelines/staging/*.jar