name: DevHour pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-Configure-ci-cd-pipelines
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn clean install
      - uses: actions/upload-artifact@v3
        with:
          name: DevHour-jars
          path: '*/target/*.jar'
  package:
    needs: build
    runs-on : ubuntu-latest
    defaults:
      run:
        working-directory: 3-Configure-ci-cd-pipelines
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: DevHour-jars
      - run: cd staging && ls -la
        shell: bash
      - run: ./build-docker-images.sh /$GITHUB_WORKSPACE
        shell: bash